### ISSUE TITLE
Connection clo

### ISSUE THREAD

**Issue by kryogenic** [OKCoin/websocket#1]
Hi,

After running the websocket code for a few hours, I get this exception:
    
```
java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:446)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:225)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
```

This seems to be preventing my application from receiving updates from 'ok_usd_future_realtrades'

**Comment by vach** [comment]
I dont understand purpose of MonitorTask...

Why is it reconnecting every 5 seconds? whats the purpose of that?

**Comment by kryogenic** [comment]
MonitorTask does 2 things:
a) Sends ping every 3 seconds (or as configured here https://github.com/OKCoin/websocket/blob/master/java/src/com/okcoin/websocket/WebSocketBase.java#L63)
b) Reconnects if "startTime" isn't updated within 5 seconds (startTime is updated each time something is read from the server)

I don't know why you're asking me, or why you're asking in this issue...

**Comment by vach** [comment]
Just saw you having issue on the same topic and tried to figure out...  :)
I appreciate any answers you give.

I understand what it does, I just think its unnecessary piece of code, i mean will websocket connection close that soon? suppose we dont send or recieve something for 30 seconds (which is really hardly possible) is there a risk that it will close the connection? 

do you think pinging every X seconds helps to something aside recovering from disconnection...?

**Comment by kryogenic** [comment]
The idea is that it reconnects if at any point the server takes more than 5 seconds to respond. Things like interruptions of internet connectivity on the client will cause the server to drop the client and stop sending messages, so the connection needs to be re-established.

**Comment by vach** [comment]
Thanks :) didn't know that
